steps:
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']

  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  - name: 'node:20'
    entrypoint: npm
    args: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/mal-registry/mal-mcp-hub:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/mal-registry/mal-mcp-hub:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/mal-registry/mal-mcp-hub'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mal-mcp-hub'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/mal-registry/mal-mcp-hub:$COMMIT_SHA'
      - '--region=${_REGION}'

substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
